CPPC=c++
BIN_DIR=bin
CPPFLAGS=-lLAB2	`root-config --glibs --cflags`
es81:	src/es_81/main_81.cpp
	$(CPPC)	$^	~/repos/lab2_utils/src/statistiche.cc	~/repos/lab2_utils/src/rand_num.cc	-o	$(BIN_DIR)/$@	$(CPPFLAGS)	

run81:	es81
	$(BIN_DIR)/$^

es82:	src/es_82/main_82.cpp
	$(CPPC)	$^	~/repos/lab2_utils/src/statistiche.cc	~/repos/lab2_utils/src/rand_num.cc	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run82:	es82
	$(BIN_DIR)/$^

es83:	src/es_83/main_83.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run83:	es83
	$(BIN_DIR)/$^

es84:	src/es_84/main_84.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run84:	es84
	$(BIN_DIR)/$^

es85:	src/es_85/main_85.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run85:	es85
	$(BIN_DIR)/$^

es86:	src/es_86/main_86.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run86:	es86
	$(BIN_DIR)/$^

es87:	src/es_87/main_87.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run87:	es87
	$(BIN_DIR)/$^

es88:	src/es_88/main_88.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run88:	es88
	$(BIN_DIR)/$^

es89:	src/es_89/main_89.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run89:	es89
	$(BIN_DIR)/$^

es810:	src/es_810/main_810.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run810:	es810
	$(BIN_DIR)/$^

