CPPC=c++
BIN_DIR=bin
CPPFLAGS=`root-config --glibs --cflags`   -lLAB2
es121:	src/es_121/main_121.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run121:	es121
	$(BIN_DIR)/$^

es122:	src/es_122/main_122.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run122:	es122
	$(BIN_DIR)/$^

es123:	src/es_123/main_123.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run123:	es123
	$(BIN_DIR)/$^

es124:	src/es_124/main_124.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run124:	es124
	$(BIN_DIR)/$^

