CPPC=c++
BIN_DIR=bin
CPPFLAGS=`root-config --glibs --cflags`
es61:	src/es_61/main_61.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run61:	es61
	$(BIN_DIR)/$^

es62:	src/es_62/main_62.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run62:	es62
	$(BIN_DIR)/$^

es63:	src/es_63/main_63.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run63:	es63
	$(BIN_DIR)/$^

es64:	src/es_64/main_64.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run64:	es64
	$(BIN_DIR)/$^

es65:	src/es_65/main_65.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run65:	es65
	$(BIN_DIR)/$^

es66:	src/es_66/main_66.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run66:	es66
	$(BIN_DIR)/$^

es67:	src/es_67/main_67.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run67:	es67
	$(BIN_DIR)/$^

