CC=g++
BIN_DIR=bin

es11: src/complesso.cc	src/es1_1/main_11.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@

run11:	es11
	$(BIN_DIR)/$^

es12: src/complesso.cc	src/es1_2/main_12.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@

run12:	es12
	$(BIN_DIR)/$^

es13: src/complesso.cc	src/es1_3/main_13.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@

run13:	es13
	$(BIN_DIR)/$^