CPPC=c++
BIN_DIR=bin
CPPFLAGS=-lLAB2	`root-config --glibs --cflags`
es101:	src/es_101/main_101.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run101:	es101
	$(BIN_DIR)/$^

es102:	src/es_102/main_102.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run102:	es102
	$(BIN_DIR)/$^

es103:	src/es_103/main_103.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run103:	es103
	$(BIN_DIR)/$^

es104:	src/es_104/main_104.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run104:	es104
	$(BIN_DIR)/$^

es105:	src/es_105/main_105.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run105:	es105
	$(BIN_DIR)/$^

es106:	src/es_106/main_106.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run106:	es106
	$(BIN_DIR)/$^

