CPPC=c++
BIN_DIR=bin
CPPFLAGS=`root-config --glibs --cflags`
es71:	src/es_71/main_71.cpp
	$(CPPC)	$^	src/es_71/main_71.cc	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run71:	es71
	$(BIN_DIR)/$^

es72:	src/es_72/main_72.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run72:	es72
	$(BIN_DIR)/$^

es73:	src/es_73/main_73.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run73:	es73
	$(BIN_DIR)/$^

es74:	src/es_74/main_74.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run74:	es74
	$(BIN_DIR)/$^

es75:	src/es_75/main_75.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run75:	es75
	$(BIN_DIR)/$^

