CC=c++
BIN_DIR=bin
CFLAGS=`root-config --glibs --cflags`

es31: src/es_31/main_31.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run31:	es31
	$(BIN_DIR)/$^

es32: src/es_32/main_32.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run32:	es32
	$(BIN_DIR)/$^

es33: src/es_33/main_33.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run33:	es33
	$(BIN_DIR)/$^

es34: src/es_34/main_34.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run34:	es34
	$(BIN_DIR)/$^	1000

es35: src/es_35/main_35.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run35:	es35
	$(BIN_DIR)/$^

es36: src/es_36/main_36.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run36:	es36
	$(BIN_DIR)/$^

es37: src/es_37/main_37.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run37:	es37
	$(BIN_DIR)/$^