CC=c++
BIN_DIR=bin
CFLAGS=`root-config --glibs --cflags`

es11: src/es3_1/main_31.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@

run11:	es31
	$(BIN_DIR)/$^

es12: src/es3_2/main_32.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run12:	es32
	$(BIN_DIR)/$^

es13: src/es3_3/main_33.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run13:	es33
	$(BIN_DIR)/$^

es14: src/es3_4/main_34.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@

run14:	es34
	$(BIN_DIR)/$^

es15: src/es3_5/main_35.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run15:	es35
	$(BIN_DIR)/$^

es16: src/es3_6/main_36.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run16:	es36
	$(BIN_DIR)/$^

es17: src/es3_7/main_37.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run17:	es37
	$(BIN_DIR)/$^