CPPC=c++
BIN_DIR=bin
CPPFLAGS=`root-config --glibs --cflags`
es111:	src/es_111/main_111.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	src/es_111/pdf.cc	src/es_111/rand_num.cc	$(CPPFLAGS)

run111:	es111
	$(BIN_DIR)/$^

es112:	src/es_112/main_112.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run112:	es112
	$(BIN_DIR)/$^

es113:	src/es_113/main_113.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run113:	es113
	$(BIN_DIR)/$^

es114:	src/es_114/main_114.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run114:	es114
	$(BIN_DIR)/$^

es115:	src/es_115/main_115.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run115:	es115
	$(BIN_DIR)/$^

es116:	src/es_116/main_116.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run116:	es116
	$(BIN_DIR)/$^

es117:	src/es_117/main_117.cpp
	$(CPPC)	$^	-o	$(BIN_DIR)/$@	$(CPPFLAGS)

run117:	es117
	$(BIN_DIR)/$^

