CC=c++
BIN_DIR=bin
CFLAGS=`root-config --glibs --cflags`

es41: src/es_41/main_41.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run41:	es41
	$(BIN_DIR)/$^

es42: src/es_42/main_42.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run42:	es42
	$(BIN_DIR)/$^

es43: src/es_43/main_43.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run43:	es43
	$(BIN_DIR)/$^

es44: src/es_44/main_44.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run44:	es44
	$(BIN_DIR)/$^	1000

es45: src/es_45/main_45.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run45:	es45
	$(BIN_DIR)/$^

es46: src/es_46/main_46.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run46:	es46
	$(BIN_DIR)/$^

es47: src/es_47/main_47.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run47:	es47
	$(BIN_DIR)/$^