CC=c++
BIN_DIR=bin
CFLAGS=`root-config --glibs --cflags`

es51: src/es_51/main_51.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run51:	es51
	$(BIN_DIR)/$^

es52: src/es_52/main_52.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run52:	es52
	$(BIN_DIR)/$^

es53: src/es_53/main_53.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run53:	es53
	$(BIN_DIR)/$^

es54: src/es_54/main_54.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run54:	es54
	$(BIN_DIR)/$^

es55: src/es_55/main_55.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run55:	es55
	$(BIN_DIR)/$^

es56: src/es_56/main_56.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run56:	es56
	$(BIN_DIR)/$^

es57: src/es_57/main_57.cpp
	$(CC)	$^	-o	$(BIN_DIR)/$@	$(CFLAGS)

run57:	es57
	$(BIN_DIR)/$^